services:
  running-app-frontend:
    image: node:18-alpine
    command: sh -c "npm install && npm start"
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    volumes:
      - ./packages/frontend:/app
    env_file: "./frontend.env" # gitignored file

  activities-service:
    image: node:18-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - "3001:3001"
    working_dir: /activities-service
    volumes:
      - ./packages/activities-service:/activities-service
      - ./protos:/protos
    depends_on:
      - rabbitmq
      - activities-go-server
    env_file: "./activities-service.env" # gitignored file

  strava-ingestion-service:
    image: node:18-alpine
    command: sh -c "npm install && npm run dev"
    working_dir: /strava-ingestion-service
    volumes:
      - ./packages/strava-ingestion-service:/strava-ingestion-service
      - ./protos:/protos
    env_file: "./activities-service.env" # gitignored file
    environment:
      - SERVICE_NAME=strava-ingestion-service
      - SERVICE_PORT=50052

  # activity-matching-service:
  #   image: node:18-alpine
  #   command: sh -c "npm install && npm run dev"
  #   working_dir: /activity-matching-service
  #   volumes:
  #     - ./packages/activity-matching-service:/activity-matching-service
  #     - ./protos:/protos
  #   env_file: "./activities-service.env" # gitignored file
  #   environment:
  #     - SERVICE_NAME=activity-matching-service
  #     - SERVICE_PORT=50055

  activities-go-server:
    build:
      dockerfile: ./packages/activities-go-server/Dockerfile
      context: ./packages/activities-go-server
      target: dev # This is the same dev that is in our Dockerfile stages.
    working_dir: /app
    volumes:
      - ./packages/activities-go-server:/app
    env_file: "./activities-service.env" # gitignored file
    ports:
      - "50051:50051"
    environment:
      - SERVICE_NAME=activity-matching-service
      - SERVICE_PORT=50051

  tcp-service:
    image: node:18-alpine
    command: sh -c "npm install && npm run start"
    ports:
      - "7070:7070"
    working_dir: /tcp-server
    volumes:
      - ./packages/tcp-server:/tcp-server

  image-service:
    image: node:18-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - "3002:3002"
    working_dir: /image-service
    volumes:
      - ./packages/image-service:/image-service
    env_file: "./image-service.env" # gitignored file

  strava-couch-db:
    image: couchdb:3
    volumes:
      - couch-db-data:/home/couchdb/data:/opt/couchdb/data
    ports:
      - "5984:5984"
    env_file: "./strava-couch-db.env"

  strava-mysql:
    image: mysql:8.0
    volumes:
      - strava-user-data:/var/lib/mysql
    env_file: "./strava-couch-db.env" # gitignored file

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server

volumes:
  redis-data:
  couch-db-data:
  strava-user-data:
