type Visibility = 'everyone' | Visibility;

type ActivityDetails = {
  _id: string,
  _rev: string,
  resource_state: number,
  athlete: {
    id: number,
    resource_state: numberr
  },
  name: string,
  distance: number,
  moving_time: number,
  elapsed_time: number,
  total_elevation_gain: number,
  type: string,
  sport_type: string,
  workout_type: string,
  id: number,
  start_date: string,
  start_date_local: string,
  timezone: string,
  utc_offset: number,
  location_city: string,
  location_state: string,
  location_country: string,
  achievement_count: number,
  kudos_count: number,
  comment_count: number,
  athlete_count: number,
  photo_count: number,
  map: {
    id: number,
    polyline: string,
    resource_state: number,
    summary_polyline: string,
  },
  trainer: boolean,
  commute: boolean,
  manual: boolean,
  private: boolean,
  visibility: Visibility,
  flagged: boolean,
  gear_id: string,
  start_latlng: LatLng,
  end_latlng: LatLng,
  average_speed: number,
  max_speed: number,
  average_watts: number,
  max_watts: number,
  weighted_average_watts: number,
  device_watts: boolean,
  kilojoules: number,
  has_heartrate: boolean,
  average_heartrate: number,
  max_heartrate: number,
  heartrate_opt_out: boolean,
  display_hide_heartrate_option: boolean,
  elev_high: number,
  elev_low: number,
  upload_id: number,
  upload_id_str: string,
  external_id: string,
  from_accepted_tag: boolean,
  pr_count: number,
  total_photo_count: number,
  has_kudoed: boolean,
  description: null,
  calories: number,
  perceived_exertion: null,
  prefer_perceived_exertion: null,
  segment_efforts: Array<{
    id: number,
    resource_state: number,
    name: string,
    activity: {
      id: number,
      visibility: Visibility,
      resource_state: number,
    },
    athlete: {
      id: number,
      resource_state: number,
    },
    elapsed_time: number,
    moving_time: number,
    start_date: string,
    start_date_local: string,
    distance: number,
    start_index: number,
    end_index: number,
    device_watts: boolean,
    average_watts: number,
    average_heartrate: number,
    max_heartrate: number,
    segment: {
      id: number,
      resource_state: number,
      name: string,
      activity_type: string,
      distance: number,
      average_grade: number,
      maximum_grade: number,
      elevation_high: number,
      elevation_low: number,
      start_latlng: LatLng,
      end_latlng: LatLng,
      elevation_profile: null,
      elevation_profiles: null,
      climb_category: number,
      city: string,
      state: string,
      country: string,
      private: boolean,
      hazardous: boolean,
      starred: boolean
    },
    pr_rank: null | number,
    achievements: [],
    visibility: Visibility,
    hidden: boolean
  }>,
  splits_metric: Array<{
      distance: number,
      elapsed_time: number,
      elevation_difference: number,
      moving_time: number,
      split: number,
      average_speed: number,
      average_grade_adjusted_speed: number,
      average_heartrate: number,
      pace_zone: number,
    }>,
  splits_standard: Array<{
      distance: number,
      elapsed_time: number,
      elevation_difference: number,
      moving_time: number,
      split: number,
      average_speed: number,
      average_grade_adjusted_speed: number,
      average_heartrate: number,
      pace_zone: number,
    }>,
  laps: Array<{
    id: number,
    resource_state: number,
    name: string,
    activity: {
      id: number,
      visibility: Visibility,
      resource_state: number,
    },
    athlete: {
      id: number,
      resource_state: number,
    },
    elapsed_time: number,
    moving_time: number,
    start_date: string,
    start_date_local: string,
    distance: number,
    average_speed: number,
    max_speed: number,
    lap_index: number,
    split: number,
    start_index: number,
    end_index: number,
    total_elevation_gain: number,
    device_watts: boolean,
    average_watts: number,
    average_heartrate: number,
    max_heartrate: number,
    pace_zone: number,
  }>,
  best_efforts: Array<{
    id: number,
    resource_state: number,
    name: string,
    activity: {
      id: number,
      visibility: Visibility,
      resource_state: number,
    },
    athlete: {
      id: number,
      resource_state: number,
    },
    elapsed_time: number,
    moving_time: number,
    start_date: string,
    start_date_local: string,
    distance: number,
    pr_rank: null | number,
    achievements: [],
    start_index: number,
    end_index: number
  }>,
  gear: {
    id: number,
    primary: boolean,
    name: string,
    nickname: null,
    resource_state: number,
    retired: boolean,
    distance: number,
    converted_distance: number
  },
  photos: {
    primary: null,
    count: number,
  },
  stats_visibility: Array<{
    type: 'heart_rate' | 'pace' | 'power' | 'speed' | 'calories',
    visibility: Visibility
  }>,
  hide_from_home: boolean,
  device_name: string,
  embed_token: string,
  similar_activities: {
    effort_count: number,
    average_speed: number,
    min_average_speed: number,
    mid_average_speed: number,
    max_average_speed: number,
    pr_rank: null | number,
    frequency_milestone: null,
    trend: {
      speeds: Array<number>,
      current_activity_index: number,
      min_speed: number,
      mid_speed: number,
      max_speed: number,
      direction: number,
    },
    resource_state: number,
  },
  available_zones: []
}