export namespace ICU_API_Response {
  export type ICU_STREAM_TYPES =
    | 'time'
    | 'watts'
    | 'cadence'
    | 'heartrate'
    | 'distance'
    | 'altitude'
    | 'latlng'
    | 'velocity_smooth'
    | 'torque'
    | 'fixed_altitude'
    ;

  export type ICU_Streams = {
    type: ICU_STREAM_TYPES;
    name: string | null;
    data: (number | null)[];
    data2: number[] | null;
    valueTypeIsArray: boolean;
    anomalies: [{
      start_index: number;
      end_index: number;
      value: number;
      valueEnd: number;
    }] | null;
    custom: boolean;
    allNull: boolean;
  }[];

  export type ICU_Attachment = {
    id: string;
    filename: string;
    mimetype: string;
    url: string;
  };

  export type ICU_Group = {
    start_index: number;
    distance: number;
    moving_time: number;
    elapsed_time: number;
    average_watts: number;
    average_watts_alt: number;
    average_watts_alt_acc: number;
    min_watts: number;
    max_watts: number;
    average_watts_kg: number;
    max_watts_kg: number;
    intensity: number;
    w5s_variability: number;
    weighted_average_watts: number;
    training_load: number;
    joules: number;
    joules_above_ftp: number;
    decoupling: number;
    avg_lr_balance: number;
    average_dfa_a1: number;
    average_epoc: number;
    wbal_start: number;
    wbal_end: number;
    average_respiration: number;
    average_tidal_volume: number;
    average_tidal_volume_min: number;
    zone: number;
    zone_min_watts: number;
    zone_max_watts: number;
    average_speed: number;
    min_speed: number;
    max_speed: number;
    gap: number;
    average_heartrate: number;
    min_heartrate: number;
    max_heartrate: number;
    average_cadence: number;
    min_cadence: number;
    max_cadence: number;
    average_torque: number;
    min_torque: number;
    max_torque: number;
    total_elevation_gain: number;
    min_altitude: number;
    max_altitude: number;
    average_gradient: number;
    average_smo2: number;
    average_thb: number;
    average_smo2_2: number;
    average_thb_2: number;
    average_lactate: number;
    min_lactate: number;
    max_lactate: number;
    average_stance_time: number;
    average_vertical_oscillation: number;
    average_vertical_ratio: number;
    average_step_length: number;
    average_stance_time_percent: number;
    average_stance_time_balance: number;
    average_vertical_speed: number;
    average_leg_spring_stiffness: number;
    average_impact_loading_rate: number;
    average_temp: number;
    average_weather_temp: number;
    average_feels_like: number;
    average_wind_speed: number;
    average_wind_gust: number;
    prevailing_wind_deg: number;
    average_yaw: number;
    headwind_percent: number;
    tailwind_percent: number;
    strain_score: number;
    ss_p_max: number;
    ss_w_prime: number;
    ss_cp: number;
    id: string;
    count: number;
    average_stride: number;
  };

  export type ICU_Interval = {
    start_index: number;
    distance: number;
    moving_time: number;
    elapsed_time: number;
    average_watts: number;
    average_watts_alt: number;
    average_watts_alt_acc: number;
    min_watts: number;
    max_watts: number;
    average_watts_kg: number;
    max_watts_kg: number;
    intensity: number;
    w5s_variability: number;
    weighted_average_watts: number;
    training_load: number;
    joules: number;
    joules_above_ftp: number;
    decoupling: number;
    avg_lr_balance: number;
    average_dfa_a1: number;
    average_epoc: number;
    wbal_start: number;
    wbal_end: number;
    average_respiration: number;
    average_tidal_volume: number;
    average_tidal_volume_min: number;
    zone: number;
    zone_min_watts: number;
    zone_max_watts: number;
    average_speed: number;
    min_speed: number;
    max_speed: number;
    gap: number;
    average_heartrate: number;
    min_heartrate: number;
    max_heartrate: number;
    average_cadence: number;
    min_cadence: number;
    max_cadence: number;
    average_torque: number;
    min_torque: number;
    max_torque: number;
    total_elevation_gain: number;
    min_altitude: number;
    max_altitude: number;
    average_gradient: number;
    average_smo2: number;
    average_thb: number;
    average_smo2_2: number;
    average_thb_2: number;
    average_lactate: number;
    min_lactate: number;
    max_lactate: number;
    average_stance_time: number;
    average_vertical_oscillation: number;
    average_vertical_ratio: number;
    average_step_length: number;
    average_stance_time_percent: number;
    average_stance_time_balance: number;
    average_vertical_speed: number;
    average_leg_spring_stiffness: number;
    average_impact_loading_rate: number;
    average_temp: number;
    average_weather_temp: number;
    average_feels_like: number;
    average_wind_speed: number;
    average_wind_gust: number;
    prevailing_wind_deg: number;
    average_yaw: number;
    headwind_percent: number;
    tailwind_percent: number;
    strain_score: number;
    ss_p_max: number;
    ss_w_prime: number;
    ss_cp: number;
    id: number;
    type: 'RECOVERY' | 'WORK';
    end_index: number;
    group_id: string;
    segment_effort_ids: number[];
    start_time: number;
    end_time: number;
    label: string;
    average_stride: number;
  };

  export type ICU_CustomZone = {
    code: string;
    zones: {
      id: string;
      start: number;
      end: number;
      start_value: number;
      end_value: number;
      secs: number;
    }[];
  };

  export type ICU_AnalysisIssue = {
    type: 'script_failed';
    message: string;
    custom_item_id: number;
  };

  export type ICU_Gear = {
    id: string;
    name: string;
    distance: number;
    primary: false;
  };

  export type ICU_Achievement = {
    id: string;
    type: 'BEST_POWER' | 'FTP_UP' | 'LTHR_UP' | 'BEST_PACE';
    message: string;
    watts: number;
    secs: number;
    value: number;
    distance: number;
    pace: number;
    point: {
      start_index: number;
      end_index: number;
      secs: number;
      value: number;
    };
  };

  export type ICU_Activity = {
    id: string;
    start_date_local: string;
    type: string;
    icu_ignore_time: boolean;
    icu_pm_cp: number;
    icu_pm_w_prime: number;
    icu_pm_p_max: number;
    icu_pm_ftp: number;
    icu_pm_ftp_secs: number;
    icu_pm_ftp_watts: number;
    icu_ignore_power: boolean;
    icu_rolling_cp: number;
    icu_rolling_w_prime: number;
    icu_rolling_p_max: number;
    icu_rolling_ftp: number;
    icu_rolling_ftp_delta: number;
    icu_training_load: number;
    icu_atl: number;
    icu_ctl: number;
    ss_p_max: number;
    ss_w_prime: number;
    ss_cp: number;
    paired_event_id: number;
    icu_ftp: number;
    icu_joules: number;
    icu_recording_time: number;
    elapsed_time: number;
    icu_weighted_avg_watts: number;
    carbs_used: number;
    name: string;
    description: string;
    start_date: string;
    distance: number;
    icu_distance: number;
    moving_time: number;
    coasting_time: number;
    total_elevation_gain: number;
    total_elevation_loss: number;
    timezone: string;
    trainer: boolean;
    sub_type: 'NONE' | 'COMMUTE' | 'WARMUP' | 'COOLDOWN' | 'RACE';
    commute: boolean;
    race: boolean;
    max_speed: number;
    average_speed: number;
    device_watts: boolean;
    has_heartrate: boolean;
    max_heartrate: number;
    average_heartrate: number;
    average_cadence: number;
    calories: number;
    average_temp: number;
    min_temp: number;
    max_temp: number;
    avg_lr_balance: number;
    average_stance_time: number;
    average_vertical_oscillation: number;
    average_vertical_ratio: number;
    average_step_length: number;
    average_stance_time_percent: number;
    average_stance_time_balance: number;
    average_vertical_speed: number;
    average_leg_spring_stiffness: number;
    average_impact_loading_rate: number;
    gap: number;
    gap_model: 'NONE' | 'STRAVA_RUN';
    use_elevation_correction: boolean;
    gear: ICU_Gear;
    perceived_exertion: number;
    device_name: string;
    power_meter: string;
    power_meter_serial: string;
    power_meter_battery: string;
    crank_length: number;
    external_id: string;
    file_sport_index: number;
    file_type: string;
    icu_athlete_id: string;
    /** date string */
    created: string;
    /** date string */
    icu_sync_date: string;
    /** date string */
    analyzed: string;
    icu_w_prime: number;
    p_max: number;
    threshold_pace: number;
    icu_hr_zones: number[];
    pace_zones: number[];
    lthr: number;
    icu_resting_hr: number;
    icu_weight: number;
    icu_power_zones: number[];
    icu_sweet_spot_min: number;
    icu_sweet_spot_max: number;
    icu_power_spike_threshold: number;
    trimp: number;
    icu_warmup_time: number;
    icu_cooldown_time: number;
    icu_chat_id: number;
    icu_ignore_hr: boolean;
    ignore_velocity: boolean;
    ignore_pace: boolean;
    ignore_parts: {
      start_index: number;
      end_index: number;
      power: boolean;
      pace: boolean;
      hr: false;
    }[];
    icu_training_load_data: number;
    interval_summary: string[];
    skyline_chart_bytes: string[];
    stream_types: string[];
    has_weather: boolean;
    has_segments: boolean;
    power_field_names: string[];
    power_field: string;
    icu_zone_times: {
      id: string;
      secs: number;
    }[];
    icu_hr_zone_times: number[];
    pace_zone_times: number[];
    gap_zone_times: number[];
    use_gap_zone_times: boolean;
    custom_zones: ICU_CustomZone[];
    tiz_order: 'POWER_HR_PACE' | 'POWER_PACE_HR' | 'HR_POWER_PACE' | 'HR_PACE_POWER' | 'PACE_POWER_HR' | 'PACE_HR_POWER';
    polarization_index: number;
    icu_achievements: ICU_Achievement[];
    icu_intervals_edited: boolean;
    lock_intervals: boolean;
    icu_lap_count: number;
    icu_joules_above_ftp: number;
    icu_max_wbal_depletion: number;
    icu_hrr: {
      start_index: number;
      end_index: number;
      start_time: number;
      end_time: number;
      start_bpm: number;
      end_bpm: number;
      average_watts: number;
      hrr: number;
    };
    icu_sync_error: string;
    icu_color: string;
    icu_power_hr_z2: number;
    icu_power_hr_z2_mins: number;
    icu_cadence_z2: number;
    icu_rpe: number;
    feel: number;
    kg_lifted: number;
    decoupling: number;
    icu_median_time_delta: number;
    p30s_exponent: number;
    workout_shift_secs: number;
    strava_id: string;
    lengths: number;
    pool_length: number;
    compliance: number;
    coach_tick: number;
    source: 'STRAVA' | 'UPLOAD' | 'MANUAL' | 'GARMIN_CONNECT' | 'OAUTH_CLIENT' | 'DROPBOX' | 'POLAR' | 'SUUNTO' | 'COROS' | 'WAHOO' | 'ZWIFT' | 'ZEPP' | 'CONCEPT2' | 'HUAWEI';
    oauth_client_id: number;
    oauth_client_name: string;
    average_altitude: number;
    min_altitude: number;
    max_altitude: number;
    power_load: number;
    hr_load: number;
    pace_load: number;
    hr_load_type: 'AVG_HR' | 'HR_ZONES' | 'HRSS';
    pace_load_type: 'SWIM' | 'Run';
    tags: string[];
    attachments: ICU_Attachment[];
    recording_stops: number[];
    average_weather_temp: number;
    min_weather_temp: number;
    max_weather_temp: number;
    average_feels_like: number;
    min_feels_like: number;
    max_feels_like: number;
    average_wind_speed: number;
    average_wind_gust: number;
    prevailing_wind_deg: number;
    headwind_percent: number;
    tailwind_percent: number;
    average_clouds: number;
    max_rain: number;
    max_snow: number;
    carbs_ingested: number;
    route_id: number;
    analysis_issues: ICU_AnalysisIssue[];
    icu_intensity: number;
    pace: number;
    icu_efficiency_factor: number;
    athlete_max_hr: number;
    group: string;
    icu_power_hr: number;
    session_rpe: number;
    average_stride: number;
    icu_average_watts: number;
    icu_variability_index: number;
    strain_score: number;
    icu_intervals: ICU_Interval[];
    icu_groups: ICU_Group[];
  };
}


