// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: protos/activityMatching/activity-matching-service.proto

package activityMatching

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LCSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          string                 `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Compare       []string               `protobuf:"bytes,2,rep,name=compare,proto3" json:"compare,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LCSRequest) Reset() {
	*x = LCSRequest{}
	mi := &file_protos_activityMatching_activity_matching_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LCSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LCSRequest) ProtoMessage() {}

func (x *LCSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_activityMatching_activity_matching_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LCSRequest.ProtoReflect.Descriptor instead.
func (*LCSRequest) Descriptor() ([]byte, []int) {
	return file_protos_activityMatching_activity_matching_service_proto_rawDescGZIP(), []int{0}
}

func (x *LCSRequest) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *LCSRequest) GetCompare() []string {
	if x != nil {
		return x.Compare
	}
	return nil
}

type ResponseItem struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ActivityId               string                 `protobuf:"bytes,1,opt,name=activityId,proto3" json:"activityId,omitempty"`
	LongestCommonSubsequence int32                  `protobuf:"varint,2,opt,name=longestCommonSubsequence,proto3" json:"longestCommonSubsequence,omitempty"`
	Error                    bool                   `protobuf:"varint,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ResponseItem) Reset() {
	*x = ResponseItem{}
	mi := &file_protos_activityMatching_activity_matching_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseItem) ProtoMessage() {}

func (x *ResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_protos_activityMatching_activity_matching_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseItem.ProtoReflect.Descriptor instead.
func (*ResponseItem) Descriptor() ([]byte, []int) {
	return file_protos_activityMatching_activity_matching_service_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseItem) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *ResponseItem) GetLongestCommonSubsequence() int32 {
	if x != nil {
		return x.LongestCommonSubsequence
	}
	return 0
}

func (x *ResponseItem) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

type LCSResponse struct {
	state                    protoimpl.MessageState   `protogen:"open.v1"`
	LongestCommonSubsequence map[string]*ResponseItem `protobuf:"bytes,1,rep,name=longestCommonSubsequence,proto3" json:"longestCommonSubsequence,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *LCSResponse) Reset() {
	*x = LCSResponse{}
	mi := &file_protos_activityMatching_activity_matching_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LCSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LCSResponse) ProtoMessage() {}

func (x *LCSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_activityMatching_activity_matching_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LCSResponse.ProtoReflect.Descriptor instead.
func (*LCSResponse) Descriptor() ([]byte, []int) {
	return file_protos_activityMatching_activity_matching_service_proto_rawDescGZIP(), []int{2}
}

func (x *LCSResponse) GetLongestCommonSubsequence() map[string]*ResponseItem {
	if x != nil {
		return x.LongestCommonSubsequence
	}
	return nil
}

var File_protos_activityMatching_activity_matching_service_proto protoreflect.FileDescriptor

const file_protos_activityMatching_activity_matching_service_proto_rawDesc = "" +
	"\n" +
	"7protos/activityMatching/activity-matching-service.proto\x12\x10activityMatching\":\n" +
	"\n" +
	"LCSRequest\x12\x12\n" +
	"\x04base\x18\x01 \x01(\tR\x04base\x12\x18\n" +
	"\acompare\x18\x02 \x03(\tR\acompare\"\x80\x01\n" +
	"\fResponseItem\x12\x1e\n" +
	"\n" +
	"activityId\x18\x01 \x01(\tR\n" +
	"activityId\x12:\n" +
	"\x18longestCommonSubsequence\x18\x02 \x01(\x05R\x18longestCommonSubsequence\x12\x14\n" +
	"\x05error\x18\x03 \x01(\bR\x05error\"\xf3\x01\n" +
	"\vLCSResponse\x12w\n" +
	"\x18longestCommonSubsequence\x18\x01 \x03(\v2;.activityMatching.LCSResponse.LongestCommonSubsequenceEntryR\x18longestCommonSubsequence\x1ak\n" +
	"\x1dLongestCommonSubsequenceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.activityMatching.ResponseItemR\x05value:\x028\x012p\n" +
	"\x10ActivityMatching\x12\\\n" +
	"\x1bGetLongestCommonSubsequence\x12\x1c.activityMatching.LCSRequest\x1a\x1d.activityMatching.LCSResponse\"\x00BGZEgithub.com/lucas1richard/activities-go-server/protos/activityMatchingb\x06proto3"

var (
	file_protos_activityMatching_activity_matching_service_proto_rawDescOnce sync.Once
	file_protos_activityMatching_activity_matching_service_proto_rawDescData []byte
)

func file_protos_activityMatching_activity_matching_service_proto_rawDescGZIP() []byte {
	file_protos_activityMatching_activity_matching_service_proto_rawDescOnce.Do(func() {
		file_protos_activityMatching_activity_matching_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_activityMatching_activity_matching_service_proto_rawDesc), len(file_protos_activityMatching_activity_matching_service_proto_rawDesc)))
	})
	return file_protos_activityMatching_activity_matching_service_proto_rawDescData
}

var file_protos_activityMatching_activity_matching_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_activityMatching_activity_matching_service_proto_goTypes = []any{
	(*LCSRequest)(nil),   // 0: activityMatching.LCSRequest
	(*ResponseItem)(nil), // 1: activityMatching.ResponseItem
	(*LCSResponse)(nil),  // 2: activityMatching.LCSResponse
	nil,                  // 3: activityMatching.LCSResponse.LongestCommonSubsequenceEntry
}
var file_protos_activityMatching_activity_matching_service_proto_depIdxs = []int32{
	3, // 0: activityMatching.LCSResponse.longestCommonSubsequence:type_name -> activityMatching.LCSResponse.LongestCommonSubsequenceEntry
	1, // 1: activityMatching.LCSResponse.LongestCommonSubsequenceEntry.value:type_name -> activityMatching.ResponseItem
	0, // 2: activityMatching.ActivityMatching.GetLongestCommonSubsequence:input_type -> activityMatching.LCSRequest
	2, // 3: activityMatching.ActivityMatching.GetLongestCommonSubsequence:output_type -> activityMatching.LCSResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_activityMatching_activity_matching_service_proto_init() }
func file_protos_activityMatching_activity_matching_service_proto_init() {
	if File_protos_activityMatching_activity_matching_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_activityMatching_activity_matching_service_proto_rawDesc), len(file_protos_activityMatching_activity_matching_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_activityMatching_activity_matching_service_proto_goTypes,
		DependencyIndexes: file_protos_activityMatching_activity_matching_service_proto_depIdxs,
		MessageInfos:      file_protos_activityMatching_activity_matching_service_proto_msgTypes,
	}.Build()
	File_protos_activityMatching_activity_matching_service_proto = out.File
	file_protos_activityMatching_activity_matching_service_proto_goTypes = nil
	file_protos_activityMatching_activity_matching_service_proto_depIdxs = nil
}
